name: Update Dashboard

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

permissions:
  pull-requests: write
  contents: write
  repository-projects: write
  id-token: write
  pages: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  generate-data-and-html:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Check out repo
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"
      - name: Get dependencies
        run: |
          go mod download
          pip install github-to-sqlite
      - name: Extract and load
        run: make extract
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Transform
        run: make transform
      - name: Save data
        run: |
          git config --global user.name "ci opentofu-stats"
          git config --global user.email "ci-opentofu-stats@users.noreply.github.com"
          git add data/tofu.db data/aggregates.json
          git commit -m "ETL update data $(date -u +'%Y%m%dT%H%M%SZ')"
          git push

      - uses: actions/configure-pages@v3
      - uses: actions/upload-pages-artifact@v2
        with:
          path: public
      - id: deployment
        uses: actions/deploy-pages@v2
