name: ELT

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  etl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Check out repo
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"
      - name: Get dependencies
        run: |
          go mod download
          pip install github-to-sqlite
      - name: Extract and load
        run: make extract
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Transform
        run: make transform
      - name: Save data
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "ci-opentofu-stats@users.noreply.github.com"
          git add data/tofu.db data/aggregates.json
          git commit -m "ETL update data ${date -u +%Y%m%dT%H%M%SZ}"
          git push
